//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveTeam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductFiveTeam
    {
        public int ID { get; set; }
        public string Productcode { get; set; }
        public string ProductName { get; set; }
        public Nullable<double> Price { get; set; }
        public string Picture { get; set; }
    }
}
